# .streamlit/secrets.toml
[stripe]
api_key = "EcoGigHubwillbesucessfull1111Vz6Q4d5nfg7Akaw"

[app]
base_url = "https://tu-app.streamlit.app"

[waldonia]
api_key = "wld_Ijdxn3qbNolexkPzGC1J8gYFjsYkjpD7Ovxl8PFRFdVt9ApxLNSJtjbHq646t8wz"