# .streamlit/secrets.toml
[stripe]
api_key = "sk_test_xxxxxxxxxxx"

[app]
base_url = "https://tu-app.streamlit.app"

[waldonia]
api_key = "wld_Ijdxn3qbNolexkPzGC1J8gYFjsYkjpD7Ovxl8PFRFdVt9ApxLNSJtjbHq646t8wz"